---

- name: Install bluez, bluez-utils, pipewire-pulse, pavucontrol
  pacman:
    name:
      - bluez
      - bluez-utils
      - pipewire-pulse
      # - pulseaudio-dlna
      - pavucontrol
    state: present
  become: yes

- name: Enable and start bluetooth
  systemd:
    name: bluetooth
    enabled: yes
    state: started
  become: yes

- name: Ensure AutoEnable=true is in section [Policy] in /etc/bluetooth/main.conf
  ini_file:
    path: /etc/bluetooth/main.conf
    section: Policy
    option: AutoEnable
    value: "true"
    backup: yes
  become: yes

# - name: Copy pulseaudio-dlna.service
#   copy:
#     src: systemd/user/pulseaudio-dlna.service
#     dest: "{{ ansible_user_dir }}/.config/systemd/user/"
