---

- name: Install cups, ghostscript
  pacman:
    name:
      - cups
      - ghostscript
    state: present
  become: yes

- name: Enable cups.socket
  systemd:
    name: cups.socket
    enabled: yes
  become: yes
