---

- name: Install firefox
  flatpak:
    name: org.mozilla.firefox
    state: present
  become: yes

- name: Override --socket=wayland
  shell: flatpak override --socket=wayland org.mozilla.firefox
  become: yes

- name: Set as default web browser
  shell: xdg-settings set default-web-browser org.mozilla.firefox.desktop

# https://mastransky.wordpress.com/2020/06/03/firefox-on-fedora-finally-gets-va-api-on-wayland/
# - name: Install libva-intel-driver, libva-utils
#   pacman:
#     name:
#       - libva-intel-driver
#       - libva-utils
#     state: present
#   become: yes

- name: Install xdg-desktop-portal-wlr
  pacman:
    name: xdg-desktop-portal-wlr
    state: present
  become: yes

- name: Configure user service environment variables
  copy:
    src: environment.d
    dest: "{{ ansible_user_dir }}/.config/"

