---

- name: Install noto-fonts, noto-fonts-cjk, noto-fonts-emoji, powerline-fonts, ttf-font-awesome
  pacman:
    name:
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - powerline-fonts
      - ttf-font-awesome
      - ttf-nerd-fonts-symbols
    state: present
  become: yes
