---

- name: Install imv, mpv, zathura, zathura-pdf-mupdf
  pacman:
    name:
      - imv
      - mpv
      # - pulseaudio-dlna
      - zathura
      - zathura-pdf-mupdf
    state: present
  become: yes

- name: Create symbolic link imvr to imv
  file:
    src: /usr/bin/imv
    dest: /usr/local/bin/imvr
    state: link
  become: yes
  tags: nnn

- name: Copy mpv config
  copy:
    src: mpv
    dest: "{{ ansible_user_dir }}/.config/"

# - name: Copy pulseaudio-dlna.service
#   copy:
#     src: systemd/user/pulseaudio-dlna.service
#     dest: "{{ ansible_user_dir }}/.config/systemd/user/"
