---

- name: Install modemmanager, networkmanager, nm-connection-editor, wireguard-tools
  pacman:
    name:
      - modemmanager
      - networkmanager
      - nm-connection-editor
      - wireguard-tools
    state: present
  become: yes

- name: Enable and start NetworkManager
  systemd:
    name: NetworkManager
    enabled: yes
    state: started
  become: yes
