theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "networkmanager"
primary_only = true

[[block]]
block = "battery"

[[block]]
block = "disk_space"

[[block]]
block = "memory"

[[block]]
block = "cpu"

[[block]]
block = "load"

[[block]]
block = "time"
