---

- name: Install aws-cli-v2-bin
  shell: paru -S --needed --noconfirm aws-cli-v2-bin || /bin/true

- name: Config fish for aws
  copy:
    src: fish/aws.fish
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
  tags: fish
