---

- import_tasks: fzf.yml
  tags: fzf
- import_tasks: yarn.yml    # required by plugin installation (ex.: iamcco/markdown-preview.nvim)
  tags: yarn

- name: Install fd, neovim, ripgrep
  pacman:
    name:
      - fd
      - neovim
      - ripgrep
    state: present
  become: yes

- name: Config fish for neovim
  copy:
    src: fish/neovim.fish
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
  tags: fish

- name: Copy neovim config
  copy:
    src: neovim/
    dest: "{{ ansible_user_dir }}/.config/nvim/"

- name: Install pynvim
  pip:
    name: pynvim
    extra_args: --user
    state: latest
