---

- name: Check if paru is installed
  stat:
    path: /usr/bin/paru
  register: paru

- name: Install paru
  shell: |
    git clone https://aur.archlinux.org/paru.git
    cd paru
    makepkg --syncdeps --install --noconfirm
    cd ..
    rm -r paru
  when: paru.stat.exists == False
