---

- name: Install python, python-pip
  pacman:
    name:
      - python
      - python-pip
    state: present
  become: yes

- name: Install ansible, black, flake8, pre-commit
  pip:
    name:
      - ansible
      - black
      - flake8
      - pre-commit
      #- python-language-server
    extra_args: --user
    state: latest

- name: Config fish for python
  copy:
    src: fish/python.fish
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
  tags: fish
