---

- name: Install starship
  shell: paru -S --needed --noconfirm starship || /bin/true

- name: Config fish for starship
  copy:
    src: fish/starship.fish
    dest: "{{ ansible_user_dir }}/.config/fish/conf.d/"
  tags: fish
